name: Docker Image CI

on:
  push:
    branches: 
      - $default-branch
      - development
      - master
    tags:
      - '*.*.*-*'
  # Run tests for any PRs
  pull_request:

env:
  IMAGE_NAME: nginx

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          check_filenames: true
          check_hidden: true
  super-linter:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs:
      - codespell
      - super-linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag ${IMAGE_NAME}
    - name: Test the Docker image
      run: |
        CONTAINER_OUTPUT=$(docker run --rm -t ${IMAGE_NAME} nginx -v)
        TEST_STRING=$(echo ${CONTAINER_OUTPUT} | head -1 | cut -d' ' -f1)
        if ! [ "${TEST_STRING}" = "nginx" ]; then exit 1; fi
        #IMAGE_TAG=$IMAGE_NAME:$(date +%s)
        #docker build . --file Dockerfile --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag ${IMAGE_TAG}
    - name: Scan image
      uses: Azure/container-scan@v0
      env:
        DOCKER_CONTENT_TRUST: 1
      with:
        image-name: ${{ env.IMAGE_NAME }}
        severity-threshold: HIGH
